Log accesses to STDOUT.
If you launch under systemd, as I do, these will be available
via `journalctl -u puppet-summary.service`.

Since I was touching this code anyway the catching of errors for
the server is cleaned up too - this should look neater if you
launch two copies:

    Launching the server on http://127.0.0.1:3001
    Error: listen tcp 127.0.0.1:3001: bind: address already in use